version: '3.2'
services:
  frontend:
    build:
      context: ./
      dockerfile: docker/frontend.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: docker/php.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_USER=madetec.uz"
      - "MYSQL_DATABASE=madetec.uz"
    command: mysqld --sql_mode=""
    ports:
      - "33066:3306"
    tty: true
volumes:
  mysql:
